name: ${name}
version: ${version}
description: Regions module for vane

authors: [oddlama]
website: 'https://github.com/oddlama/vane'

depend: [vane-core, vane-portals]
softdepend: [dynmap, Vault, BlueMap]

main: org.oddlama.vane.regions.Regions
database: false

api-version: 1.19
load: STARTUP
