name: ${name}
version: ${version}
description: Trifles module for vane

authors: 
  - oddlama
website: 'https://github.com/oddlama/vane'

main: org.oddlama.vane.trifles.Trifles

api-version: '1.21'
load: STARTUP
dependencies:
  server:
    vane-core:
      required: true
      load: BEFORE