name: ${name}
version: ${version}
description: Portals module for vane

authors: [oddlama]
website: 'https://github.com/oddlama/vane'

depend: [vane-core]
softdepend: [dynmap, BlueMap]

main: org.oddlama.vane.portals.Portals
database: false

api-version: 1.19
load: STARTUP
