name: ${name}
version: ${version}
description: Enchantments module for vane

authors: [oddlama]
website: 'https://github.com/oddlama/vane'

depend: [vane-core]

main: org.oddlama.vane.enchantments.Enchantments
database: false

api-version: 1.19
load: STARTUP
